language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
install:
  - "pip install django==$DJANGO_VERSION --use-mirrors"
  - "pip install nose --use-mirrors"
script:
  - "nosetests tests"
